profile:
  links:
    blog: "https://flower.codes"
    rss: "https://flower.codes/feed.xml"
  about: |
    Hi there. I'm <strong>Zach</strong>. Welcome to my profile. Obviously I'm experimenting with that classic <strong>MySpace</strong> look (within the limitations of <strong>GitHub's</strong> markdown renderer). Like a lot of developers my age, tweaking the look and feel on a MySpace page was one of my earliest exposures to HTML and JavaScript, so this felt like an appropriate homage to that time. Feel free to drop me a line or open a PR if you have any ideas on how to improve the attempt.

    A few things I want to do at some point:

    • <del>Automatically update the recent blog post list</del>
    • <del>Update the "friend count" number</del>
    • <del>Render the "friend count" number as an SVG so it can be the proper color (red)</del>
    • Figure out a realistic comments system
    • Kill the GitHub table for the friends list and use an SVG to better match the style
  meet: I have a pretty big list of nerd heroes that I'd love to meet someday, but after taking a trip down memory lane to put this profile together, I'd love to meet AOL's "You've Got Mail" guy. Preferably over the phone. Don't want to ruin the magic.
  friends:
    favorites:
      - name: Tom
        url: 'https://web.archive.org/web/20050407064112/http://www.myspace.com:80/tom'
        image: 'public/img/tom.jpg'
      - name: Clippy
        url: 'https://en.wikipedia.org/wiki/Office_Assistant'
        image: 'public/img/clippy.gif'